name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Needed for creating releases
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Enable multi-arch builds (arm64 / amd64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract version (if tag push) — strips the "v"
      - name: Extract version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Build and push images
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPO }}:latest
            ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_REPO }}:${{ env.VERSION || '' }}

      # Create GitHub Release automatically when tag pushed
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true

